spring:
  application:
    name: user-server

server:
  port: 8763
  context-path: /user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      filter-order: 3

logging:
  level:
    root: info
