spring:
  application:
    name: auth-server

server:
  port: 8762
  context-path: /auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      filter-order: 3
